### Numpy介绍
numpy是python中科学计算的基础包。<br>
提供多维数组对象、各种派生对象（例如掩码数组和矩阵）以及用于对数组进行快速操作的各种方法。<br>
包括数学、逻辑、形状操作、排序、选择、I/O、离散傅里叶变换、基本线性代数、基本统计运算、随机模拟等等。<br>
numpy的部分功能如下：<br>
&emsp;ndarray，一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组；<br>
&emsp;用于对整组数据进行快速运算的标准数学函数；<br>
&emsp;用于读写磁盘数据的工具以及用于操作内存映射文件的工具；<br>
&emsp;线性代数、随机数生成以及傅里叶变换功能；<br>
&emsp;用于集成由C、C++、Fortran等语言编写的代码的API。<br>
numpy数组（ndarry）的核心特性：<br>
&emsp;多维性：支持0维（标量）、1维（向量）、2维（矩阵）及更高维数组；<br>
&emsp;同质性：所有元素类型必须一致（通过dtype指定）；<br>
&emsp;高效性：基于连续内存块存储、支持向量化运算。<br>
#### 1.ndarry的特性
##### 多维性

In [14]:
import numpy as np

arr1 = np.array(5)  # 创建0维ndarry数组
print(arr1)
print(f'arr1的维度：{arr1.ndim}')
arr2 = np.array([1, 2, 3])  # 创建1维ndarry数组
print(arr2)
print(f'arr2的维度：{arr2.ndim}')
arr3 = np.array([[1, 2, 3], [4, 5, 6]])  # 创建2维ndarry数组
print(arr3)
print(f'arr3的维度：{arr3.ndim}')

5
arr1的维度：0
[1 2 3]
arr2的维度：1
[[1 2 3]
 [4 5 6]]
arr3的维度：2


##### 同质性

In [13]:
import numpy as np

arr1 = np.array([1, 'hello'])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr1)
arr2 = np.array([1, 2.5])
print(arr2)

['1' 'hello']
[1.  2.5]


#### 2.ndarry的属性
属性名称|通俗解释|使用示例
:-|:-:|:-
shape|数组的形状：行数和列数（或更高维度的尺寸）|arr.shape
ndim|维度数量：数组是几维的（1维、2维、3维等）|arr.ndim
size|总元素个数：数组中所有元素的总数|arr.size
dtype|元素类型：数组中元素的类型（整数、浮点数等）|arr.dtype
T|转置：行变列，列变行|arr.T
itemsize|单个元素占用的内存字节数|arr.itemsize
nbytes|数组总内存占用量：size*itemsize|arr.nbytes
flags|内存存储方式：是否连续存储（高级优化）|arr.flags

In [25]:
import numpy as np

arr1 = np.array(1)
print(arr1)
print(f'数组的形状：{arr1.shape}')
print(f'数组的维度：{arr1.ndim}')
print(f'元素的个数：{arr1.size}')
print(f'元素的类型：{arr1.dtype}')
print(f'元素的转置：{arr1.T}')
arr2 = np.array([1, 2, 3])
print(arr2)
print(f'数组的形状：{arr2.shape}')
print(f'数组的维度：{arr2.ndim}')
print(f'元素的个数：{arr2.size}')
print(f'元素的类型：{arr2.dtype}')
print(f'元素的转置：{arr2.T}')
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print(f'数组的形状：{arr3.shape}')
print(f'数组的维度：{arr3.ndim}')
print(f'元素的个数：{arr3.size}')
print(f'元素的类型：{arr3.dtype}')
print(f'元素的转置：{arr3.T}')

1
数组的形状：()
数组的维度：0
元素的个数：1
元素的类型：int64
元素的转置：1
[1 2 3]
数组的形状：(3,)
数组的维度：1
元素的个数：3
元素的类型：int64
元素的转置：[1 2 3]
[[1 2 3]
 [4 5 6]]
数组的形状：(2, 3)
数组的维度：2
元素的个数：6
元素的类型：int64
元素的转置：[[1 4]
 [2 5]
 [3 6]]
