### Numpy介绍
numpy是python中科学计算的基础包。<br>
提供多维数组对象、各种派生对象（例如掩码数组和矩阵）以及用于对数组进行快速操作的各种方法。<br>
包括数学、逻辑、形状操作、排序、选择、I/O、离散傅里叶变换、基本线性代数、基本统计运算、随机模拟等等。<br>
numpy的部分功能如下：<br>
&emsp;ndarray，一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组；<br>
&emsp;用于对整组数据进行快速运算的标准数学函数；<br>
&emsp;用于读写磁盘数据的工具以及用于操作内存映射文件的工具；<br>
&emsp;线性代数、随机数生成以及傅里叶变换功能；<br>
&emsp;用于集成由C、C++、Fortran等语言编写的代码的API。<br>
numpy数组（ndarry）的核心特性：<br>
&emsp;多维性：支持0维（标量）、1维（向量）、2维（矩阵）及更高维数组；<br>
&emsp;同质性：所有元素类型必须一致（通过dtype指定）；<br>
&emsp;高效性：基于连续内存块存储、支持向量化运算。<br>
### 1.ndarry的特性
#### 多维性

In [ ]:
import numpy as np

arr1 = np.array(5)  # 创建0维ndarry数组
print(arr1)
print(f'arr1的维度：{arr1.ndim}')
arr2 = np.array([1, 2, 3])  # 创建1维ndarry数组
print(arr2)
print(f'arr2的维度：{arr2.ndim}')
arr3 = np.array([[1, 2, 3], [4, 5, 6]])  # 创建2维ndarry数组
print(arr3)
print(f'arr3的维度：{arr3.ndim}')

#### 同质性

In [ ]:
import numpy as np

arr1 = np.array([1, 'hello'])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr1)
arr2 = np.array([1, 2.5])
print(arr2)

### 2.ndarry的属性
属性名称|通俗解释|使用示例
:-|:-:|:-
shape|数组的形状：行数和列数（或更高维度的尺寸）|arr.shape
ndim|维度数量：数组是几维的（1维、2维、3维等）|arr.ndim
size|总元素个数：数组中所有元素的总数|arr.size
dtype|元素类型：数组中元素的类型（整数、浮点数等）|arr.dtype
T|转置：行变列，列变行|arr.T
itemsize|单个元素占用的内存字节数|arr.itemsize
nbytes|数组总内存占用量：size*itemsize|arr.nbytes
flags|内存存储方式：是否连续存储（高级优化）|arr.flags

In [ ]:
import numpy as np

arr1 = np.array(1)
print(arr1)
print(f'数组的形状：{arr1.shape}')
print(f'数组的维度：{arr1.ndim}')
print(f'元素的个数：{arr1.size}')
print(f'元素的类型：{arr1.dtype}')
print(f'元素的转置：{arr1.T}')
arr2 = np.array([1, 2, 3])
print(arr2)
print(f'数组的形状：{arr2.shape}')
print(f'数组的维度：{arr2.ndim}')
print(f'元素的个数：{arr2.size}')
print(f'元素的类型：{arr2.dtype}')
print(f'元素的转置：{arr2.T}')
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print(f'数组的形状：{arr3.shape}')
print(f'数组的维度：{arr3.ndim}')
print(f'元素的个数：{arr3.size}')
print(f'元素的类型：{arr3.dtype}')
print(f'元素的转置：{arr3.T}')

### 3.ndarray的创建
基础构造：适用于手动创建小规模数组或复制已有的数据。<br>
预定义形状填充：用于快速初始化固定形状的数组（如全0占位、全1初始化）。<br>
基于数值范围生成：生成数值序列，常用于模拟时间序列、坐标网格等。<br>
特殊矩阵生成：数学运算专用（如线性代数中的单位矩阵）。<br>
随机数组生产：模拟实验数据、初始化神经网络权重等场景。<br>
高级构造方法：处理非结构化数据（如文件、字符串）或通过函数生成复杂数组。<br>

<table>
    <tr>
        <td>用途</td>
        <td colspan="5">方法</td>
   </tr>
   <tr>
        <td>基础构造</td>
        <td>np.array()</td>
        <td colspan="4">np.copy()</td>
   </tr>
    <tr>
        <td >预定义形状填充</td> 
        <td >np.zeros()</td>
        <td >np.ones()</td>
        <td >np.empty()</td>
        <td >np.full()</td>
    </tr>
    <tr>
        <td >基于数值范围生成</td>
        <td >np.arange()</td>
        <td >np.linsapce()</td>
        <td colspan="2">np.logspace()</td>
    </tr>
    <tr>
        <td >特殊矩阵生成</td>
        <td >np.eye()</td>
        <td >np.diag()</td>
        <td colspan="4">np.logspace()</td>
    </tr>
    <tr>
        <td >随机数组生成</td>
        <td >np.random.rand()</td>
        <td >np.random.randn()</td>
        <td colspan="2">np.random.randint()</td>
    </tr>
    <tr>
        <td >高级构造方法</td>
        <td >np.array()</td>
        <td >np.loadtxt()</td>
        <td colspan="2">np.fromfunction()</td>
    </tr>
</table>


In [ ]:
import numpy as np

# 基础的创建方法
list1 = [1, 2, 3]
arr1 = np.array(list1)
print(arr1)
arr2 = np.copy(arr1)
print(arr2)
arr1[0] = 8
print(arr1)
print(arr2)

# 预定义形状填充
arr3 = np.zeros((2, 3), dtype=int)  # 默认浮点型
print(arr3)
arr4 = np.ones((2, 3))
print(arr4)
arr5 = np.empty((4, 2))
print(arr5)
arr6 = np.full((4, 3), 2026)
print(arr6)
arr7 = np.zeros_like(arr6)
print(arr7)

# 等差数列
arr8 = np.arange(2, 10, 2)
print(arr8)
# 等间隔数列
arr9 = np.linspace(0, 10, 5, dtype=int)
print(arr9)
# 对数间隔数列
arr10 = np.logspace(0, 4, 3, base=2, dtype=int)
print(arr10)

#### ndarry矩阵
<p>矩阵是由行和列排列成的矩形数组</p>
<img src="../assets/chapter_20260123220028.png">
<p>形状：这个矩阵有2行3列，记作2x3矩阵。</p>
<p>元素：矩阵中的每个数字成为元素<p>

#### 特殊矩阵
<img src="../assets/chapter01_20260123220310.png">

In [ ]:
import numpy as np

###### 矩阵
# 单位矩阵
arr1 = np.eye(3, 4, dtype=int)
print(arr1)
# 对角矩阵
arr2 = np.diag([5, 1, 2, 3])
print(arr2)

###### 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr3 = np.random.rand(2, 3)
print(arr3)
# 生成指定范围之间的随机浮点数（均匀分布）
arr4 = np.random.uniform(3, 6, (2, 3))
print(arr4)
# 生成指定范围之间的随机整数（均匀分布）
arr4 = np.random.randint(3, 6, (3, 30))
print(arr4)
# 生成随机数列（正态分布）
arr5 = np.random.randn(2, 3)
print(arr5)
# 设置随机种子
np.random.seed(20)
arr6 = np.random.randint(1, 10, (2, 5))
print(arr6)

### 4.ndarray的数据类型
<img src="../assets/chapter01_20260123222841.png">

In [ ]:
import numpy as np

arr1 = np.array([1, 0, 2.0], dtype="bool")
arr2 = np.array([1, 0, 2, 2000], dtype="int8")
print(arr1)
print(arr2)

### 5.ndarry的索引与切片
<img src="../assets/chapter01_20260123223839.png">

In [ ]:
import numpy as np

# 一维数组的索引与切片
arr1 = np.random.randint(1, 100, 20)
print(arr1)

[53 23 15  5 28 76  9  7 27 80 83 79 11 34 86 18 41 83 43 61]


In [73]:
print(arr1[0])
print(arr1[:])
print(arr1[5:10])
print(arr1[arr1 > 50])
print(arr1[(arr1 > 30) & (arr1 < 50)])

53
[53 23 15  5 28 76  9  7 27 80 83 79 11 34 86 18 41 83 43 61]
[76  9  7 27 80]
[53 76 80 83 79 86 83 61]
[34 41 43]
